DemoCortex/src/Project/Demo/code/Models/ParseDataResult.cs
namespace Demo.Project.Demo.Models
{
    public class ParseDataResult
    {
        public int CustomersCount { get; set; }
        public int InteractionsCount { get; set; }
        public int PurchasesCount { get; set; }

    }
}

DemoCortex/src/Project/Demo/code/Controllers/ContactApiController.cs
using System;
using System.Threading.Tasks;
using System.Web.Http;
using Demo.Foundation.ProcessingEngine.Agents;
using Demo.Foundation.ProcessingEngine.Import;
using Demo.Foundation.ProcessingEngine.Services;
using Demo.Project.Demo.Models;

namespace Demo.Project.Demo.Controllers
{
    public class ContactApiController : ApiController
    {
        // used for register processing engine tasks from sitecore website (for debugging purposes) by calling /api/contactapi/registertasks
        public async Task<bool> RegisterTasks()
        {
            var x = new SitecoreTaskManager();
            await x.RegisterAll();
            return true;
        }

        // used for upload orders history from excel to xConnect by using Demo-Data-Explorer(can takes ~15 minutes)
        [HttpPost]
        public async Task<ParseDataResult> UploadClientsHistory()
        {
            try
            {
                var stream = await Request.Content.ReadAsStreamAsync();
                var customers = new ExcelImportProcessor().GetImportData(stream);

                var count = customers.Count;
                var index = 0;

                var purchaseService = new XConnectService();

                foreach (var c in customers)
                {
                    index++;
                    var added = await purchaseService.Add(c, true);
                    if (added)
                    {
                        Sitecore.Diagnostics.Log.Info($"Excel import: {index} from {count}: CustomerID={c.CustomerId}", this);
                    }
                    else
                    {
                        Sitecore.Diagnostics.Log.Error($"Excel import: {index} from {count}: CustomerID={c.CustomerId}", this);
                    }
                }

                return new ParseDataResult
                {
                    CustomersCount = count,
                    InteractionsCount = count,
                    PurchasesCount = customers.Count
                };
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
         
        }
    }
}

DemoCortex/src/Project/Demo/code/Controllers/DemoController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Demo.Foundation.ProcessingEngine.Models;
using Demo.Foundation.ProcessingEngine.Services;
using Sitecore.Analytics;
using Sitecore.Web;

namespace Demo.Project.Demo.Controllers
{
    public class CreateContactModel
    {
        public string Number { get; set; }
        public string Email { get; set; }
    }

    public class DemoController : Controller
    {
        // GET: Demo
        public ActionResult Index()
        {
            return View(new CreateContactModel());
        }
        public ActionResult Demo()
        {
            return View();
        }
        public ActionResult DemoVip()
        {
            return View();
        }

        public async Task<bool> CreateContact(CreateContactModel model)
        {
            var purchaseService = new XConnectService();
            var created = await purchaseService.CreateContact(XConnectService.IdentificationSource, model.Number, model.Email);
            return created;
        }

        public ActionResult EndAll(int clear = 0)
        {
            if (Tracker.Current != null)
            {
                Tracker.Current.EndVisit(clear != 0);
            }
            HttpContext.Session.Abandon();
            return Redirect("/demo");
        }

        public ActionResult IdentifyByEmail(string email)
        {
            Tracker.Current.Session.IdentifyAs(XConnectService.IdentificationSourceEmail, email);
            return Redirect("/demo");
        }

        public void RegisterTestPurchase(string email)
        {
            Tracker.Current.Session.IdentifyAs(XConnectService.IdentificationSourceEmail, email);
            var customer = Tracker.Current.Session.Contact.Identifiers.First(x => x.Source == "demo");

            var ev = Tracker.MarketingDefinitions.Outcomes[PurchaseOutcome.PurchaseEventDefinitionId];
            var outcomeData = new Sitecore.Analytics.Data.OutcomeData(ev, "USD", 112233);
            // Never saved to xConnect, must be converted into a property on a custom model
            outcomeData.CustomValues.Add("Quantity", "5"); 
            outcomeData.CustomValues.Add("CustomerId", customer.Identifier);
            outcomeData.CustomValues.Add("InvoiceId", "123");
            outcomeData.CustomValues.Add("StockCode", "1112233");

            Tracker.Current.CurrentPage.RegisterOutcome(outcomeData);
        }

        public bool Test()
        {
            return true;
        }
    }
}

DemoCortex/src/Project/Demo/code/Views/Demo/Demo.cshtml
@model dynamic

@{
    Layout = null;
}
<br/>
<img style="width:410px;border: 3px solid #000;" src="https://scontent.fmsq2-1.fna.fbcdn.net/v/t1.0-9/49530477_378802842678383_730212841969156096_n.jpg?_nc_cat=103&_nc_ht=scontent.fmsq2-1.fna&oh=6103d2a1ccf949a552b1e1bfea29360a&oe=5D44EACA" />

DemoCortex/src/Project/Demo/code/Views/Demo/DemoVip.cshtml
@model dynamic

@{
    Layout = null;
}
<br/>
<img style="width:410px;border: 3px solid #000;" src="http://fawp.ua.edu/bamadining/wp-content/uploads/sites/5/2015/06/VIP-logos-01-1024x705.png" />

DemoCortex/src/Project/Demo/code/Views/Demo/Index.cshtml
@model Demo.Project.Demo.Controllers.CreateContactModel
@using Demo.Foundation.ProcessingEngine.Facets;
@using Sitecore.Analytics;
@using Sitecore.Analytics.XConnect.Facets;
@{
    Layout = null;
}

@{
    if (!Tracker.Current.IsActive || Tracker.Current.Contact == null || Tracker.Current.Contact.IsNew)
    {
        <h1>I`m anonymous</h1>
    }
    else
    {
        var xConnectFacets = Tracker.Current.Contact.GetFacet<IXConnectFacets>("XConnectFacets");
        if (xConnectFacets!=null && xConnectFacets.Facets != null && xConnectFacets.Facets.ContainsKey(RfmContactFacet.DefaultFacetKey))
        {
            var facet = xConnectFacets.Facets[RfmContactFacet.DefaultFacetKey] as RfmContactFacet;
            if (facet != null)
            {
                <h1>My RFM is: @facet.R @facet.F @facet.M </h1>
                <h2>My cluster is: @facet.Cluster</h2>
            }
        }
    }
}

@using (Html.BeginForm("IdentifyByEmail", "Demo", FormMethod.Post, new {@class= "form-inline", style= "width:auto;float: left;" }))
{

    <div class="form-group mb-2">
        <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    </div>
  
    <button type="submit" class="btn btn-primary  mb-2" style="margin-left:10px">Identify</button>
}

<br />
@using (Html.BeginForm("EndAll", "Demo", FormMethod.Post, new { @class = "form-inline", style = "margin-top: -25px; padding-left: 10px;" }))
{

    <button class="btn btn-primary" type="submit">End Session</button>
}

DemoCortex/src/Project/Demo/code/Views/Demo/Layout.cshtml
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
@{
    Layout = null;
}
<!DOCTYPE html>
<!--[if IE 9]><html lang="en" class="ie9 no-js"><![endif]-->
<!--[if !IE]><!-->
<html lang="@Sitecore.Context.Language.CultureInfo.TwoLetterISOLanguageName">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Demo</title>

    @Html.Sitecore().VisitorIdentification()

</head>
<body>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<div class="container" style="margin-top: 49px;">
    <h1 class="text-center">Demo</h1><br/>
    @Html.Sitecore().Placeholder("main")
</div>
</body>
</html>